theme: jekyll-theme-cayman
title: Trino MCP Server
description: A Model Context Protocol (MCP) server for Trino implemented in Go
show_downloads: true
github:
  repository_url: https://github.com/tuannvm/mcp-trino
  releases_url: https://github.com/tuannvm/mcp-trino/releases
  is_project_page: true
  # Custom links for platform-specific binaries
  another_url: https://github.com/tuannvm/mcp-trino/releases/latest/download/mcp-trino-darwin-amd64
  zip_url: https://github.com/tuannvm/mcp-trino/releases/latest
  tar_url: https://github.com/tuannvm/mcp-trino/releases 